#!/bin/bash
set -euo pipefail

# Phase 6: Add a new Supabase stack to an existing VM (Path B only).
# Stores secrets in Key Vault, copies Docker Compose, configures Caddy, adds DNS.

CONFIG_FILE=".bootstrap-config"

if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "ERROR: $CONFIG_FILE not found. Run 01-init.sh first."
  exit 1
fi
source "$CONFIG_FILE"

echo "=== Phase 6: Add Project to Existing VM ==="
echo ""

if [[ "$SUPABASE_STRATEGY" != "2" ]]; then
  echo "Not adding to existing VM (strategy is not 'existing')."
  echo "Phase 6 skipped."
  exit 0
fi

if [[ -z "$VM_IP" || -z "$KV_NAME" || -z "$SSH_KEY_PATH" ]]; then
  echo "ERROR: VM_IP, KV_NAME, and SSH_KEY_PATH must be set. Check .bootstrap-config."
  exit 1
fi

SSH_CMD="ssh -i $SSH_KEY_PATH -o StrictHostKeyChecking=accept-new azureuser@$VM_IP"
KONG_PORT=$((8000 + PORT_INDEX * 100))
STUDIO_PORT=$((3000 + PORT_INDEX * 100))
POSTGRES_PORT=$((5432 + PORT_INDEX * 100))

echo "VM:          $VM_IP"
echo "Key Vault:   $KV_NAME"
echo "Kong port:   $KONG_PORT"
echo "Studio port: $STUDIO_PORT"
echo "Postgres port: $POSTGRES_PORT"
echo ""

# --- Store secrets in Key Vault ---

echo "Storing Supabase secrets in Key Vault..."

PROJECT_UPPER=$(echo "$PROJECT" | tr '[:lower:]' '[:upper:]')

kv_set() {
  local name="$1" value="$2"
  az keyvault secret set --vault-name "$KV_NAME" --name "$name" --value "$value" --output none
  echo "  $name"
}

kv_set "${PROJECT_UPPER}-JWT-SECRET" \
  "$(op read "op://$PROJECT/Supabase/jwt_secret")"
kv_set "${PROJECT_UPPER}-POSTGRES-PASSWORD" \
  "$(op read "op://$PROJECT/Supabase/postgres_password")"
kv_set "${PROJECT_UPPER}-ANON-KEY" \
  "$(op read "op://$PROJECT/Supabase/anon_key")"
kv_set "${PROJECT_UPPER}-SERVICE-ROLE-KEY" \
  "$(op read "op://$PROJECT/Supabase/service_role_key")"
kv_set "${PROJECT_UPPER}-DASHBOARD-PASSWORD" \
  "$(op read "op://$PROJECT/Supabase/dashboard_password")"

echo ""

# --- Set up Docker Compose on VM ---

echo "Setting up Supabase stack on VM..."

# Instead of sed-replacing ports in a copied compose file (fragile),
# copy the compose file as-is and use a .env file to override ports,
# container names, and volume names. The Supabase compose file already
# supports environment variable substitution for these values.

$SSH_CMD bash <<REMOTE
  set -euo pipefail

  # Create project directory
  sudo mkdir -p /opt/supabase-${PROJECT}

  # Copy docker-compose from the first project as a template (unmodified)
  TEMPLATE=\$(sudo find /opt -maxdepth 2 -name docker-compose.yml 2>/dev/null | grep -v "${PROJECT}" | head -1)
  if [[ -n "\$TEMPLATE" ]]; then
    sudo cp "\$TEMPLATE" /opt/supabase-${PROJECT}/docker-compose.yml
    echo "  Copied docker-compose from \$TEMPLATE (unmodified)"
  else
    echo "  ERROR: No existing docker-compose.yml found to use as template."
    exit 1
  fi

  # Create a .env file to override ports and naming via Docker Compose
  # environment variable substitution — no sed mutations needed.
  sudo tee /opt/supabase-${PROJECT}/.env.ports > /dev/null <<ENVFILE
# Project-specific overrides (generated by bootstrap)
COMPOSE_PROJECT_NAME=${PROJECT}
KONG_PORT=${KONG_PORT}
STUDIO_PORT=${STUDIO_PORT}
ENVFILE

  # The postgres host port is hardcoded in docker-compose.yml.
  # Docker Compose merges port lists in overrides (doesn't replace), so we
  # sed the single port line in the already-copied compose file instead.
  sudo sed -i "s|127.0.0.1:5432:5432|127.0.0.1:${POSTGRES_PORT}:5432|" \
    /opt/supabase-${PROJECT}/docker-compose.yml

  echo "  Created .env.ports: Kong=${KONG_PORT}, Studio=${STUDIO_PORT}, Postgres=${POSTGRES_PORT}"
  echo "  Container prefix: ${PROJECT}"
REMOTE

echo ""

# --- Update secret loader and restart ---

echo "Updating secret loader configuration..."
$SSH_CMD bash <<REMOTE
  set -euo pipefail

  # Add project to the PROJECTS= line in the loader config
  LOADER_CONF="/etc/supabase-loader.conf"
  if sudo test -f "\$LOADER_CONF"; then
    CURRENT_PROJECTS=\$(sudo grep '^PROJECTS=' "\$LOADER_CONF" | cut -d= -f2)
    if echo "\$CURRENT_PROJECTS" | grep -qw "${PROJECT}"; then
      echo "  ${PROJECT} already in PROJECTS."
    else
      NEW_PROJECTS="\$CURRENT_PROJECTS ${PROJECT}"
      sudo sed -i "s/^PROJECTS=.*/PROJECTS=\$NEW_PROJECTS/" "\$LOADER_CONF"
      echo "  Updated PROJECTS to: \$NEW_PROJECTS"
    fi
    # Remove any stale bare project lines (from previous broken appends)
    sudo sed -i '/^[a-z][a-z0-9-]*$/d' "\$LOADER_CONF"
  fi

  # Restart secret loader to pick up new project
  if sudo systemctl restart supabase-secret-loader 2>/dev/null; then
    echo "  Secret loader restarted."
  else
    echo "  WARNING: supabase-secret-loader service not found. Manual .env setup may be needed."
  fi

  # Wait for the loader to write the .env file before starting containers
  echo "  Waiting for .env to be generated (up to 60s)..."
  for i in \$(seq 1 12); do
    if sudo test -f "/opt/supabase-${PROJECT}/.env"; then
      echo "  .env ready."
      break
    fi
    echo "    attempt \$i/12..."
    sleep 5
  done
  if ! sudo test -f "/opt/supabase-${PROJECT}/.env"; then
    echo "  ERROR: .env not generated after 60s."
    echo "  Check: sudo systemctl status supabase-secret-loader"
    echo "  Check: sudo journalctl -u supabase-secret-loader -n 50"
    exit 1
  fi
REMOTE

echo ""

# --- Start containers ---

echo "Starting Supabase containers..."
$SSH_CMD bash <<REMOTE
  set -euo pipefail
  cd /opt/supabase-${PROJECT}
  sudo docker compose --env-file .env --env-file .env.ports up -d
  echo "  Containers starting..."

  # Wait for health
  echo "  Waiting for containers to be healthy (up to 60s)..."
  for i in \$(seq 1 12); do
    HEALTHY=\$(sudo docker compose ps --format json 2>/dev/null | jq -r '.Health // "unknown"' | grep -c "healthy" || true)
    TOTAL=\$(sudo docker compose ps --format json 2>/dev/null | jq -r '.Name' | wc -l || true)
    echo "    \${HEALTHY}/\${TOTAL} healthy (attempt \$i/12)"
    if [[ "\$HEALTHY" -ge 2 ]]; then
      break
    fi
    sleep 5
  done
REMOTE

echo ""

# --- Configure Caddy ---

echo "Adding Caddy reverse proxy rules..."
$SSH_CMD bash <<REMOTE
  set -euo pipefail

  # Check if project is already in Caddyfile
  if grep -q "${PROJECT}.db" /etc/caddy/Caddyfile 2>/dev/null; then
    echo "  ${PROJECT} already in Caddyfile."
  else
    sudo tee -a /etc/caddy/Caddyfile > /dev/null <<CADDY

${PROJECT}.db.${DOMAIN} {
    reverse_proxy localhost:${KONG_PORT}
}

studio.${PROJECT}.db.${DOMAIN} {
    reverse_proxy localhost:${STUDIO_PORT}
}
CADDY
    echo "  Added reverse proxy rules."
    sudo caddy reload --config /etc/caddy/Caddyfile 2>/dev/null || \
      sudo systemctl reload caddy
    echo "  Caddy reloaded. TLS cert will be provisioned automatically."
  fi
REMOTE

echo ""

# --- Add DNS A record ---

echo "Adding DNS A record..."

# Determine resource group for DNS zone (try common names)
DNS_RG=$(az network dns zone list --query "[?name=='db.${DOMAIN}'].resourceGroup" -o tsv 2>/dev/null || true)

if [[ -n "$DNS_RG" ]]; then
  az network dns record-set a add-record \
    --zone-name "db.${DOMAIN}" \
    --resource-group "$DNS_RG" \
    --record-set-name "${PROJECT}" \
    --ipv4-address "$VM_IP" \
    --output none 2>/dev/null || echo "  (record may already exist)"

  az network dns record-set a add-record \
    --zone-name "db.${DOMAIN}" \
    --resource-group "$DNS_RG" \
    --record-set-name "studio.${PROJECT}" \
    --ipv4-address "$VM_IP" \
    --output none 2>/dev/null || echo "  (record may already exist)"

  echo "  DNS records added:"
  echo "    ${PROJECT}.db.${DOMAIN} → $VM_IP"
  echo "    studio.${PROJECT}.db.${DOMAIN} → $VM_IP"
else
  echo "  WARNING: Could not find DNS zone 'db.${DOMAIN}' in Azure."
  echo "  Add these DNS records manually:"
  echo "    A  ${PROJECT}.db.${DOMAIN}         → $VM_IP"
  echo "    A  studio.${PROJECT}.db.${DOMAIN}  → $VM_IP"
fi

# --- Update backup script ---

echo ""
echo "Updating backup script..."
$SSH_CMD bash <<REMOTE
  if [[ -f /opt/scripts/backup.sh ]]; then
    if ! grep -q "${PROJECT}" /opt/scripts/backup.sh; then
      echo "  NOTE: Add '${PROJECT}' to the PROJECTS list in /opt/scripts/backup.sh"
    else
      echo "  ${PROJECT} already in backup script."
    fi
  fi
REMOTE

echo ""
echo "Phase 6 complete. Project added to existing VM."
echo ""
echo "  API:    https://${PROJECT}.db.${DOMAIN}"
echo "  Studio: https://studio.${PROJECT}.db.${DOMAIN}"
echo ""
echo "  Note: TLS certs will be provisioned by Caddy automatically."
echo "  DNS propagation may take a few minutes."
